notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#sayit"
    use_notice: true

language: python

python:
  - "2.7"
  - "3.3"

services:
  - elasticsearch

env:
  - MODULES="Django>=1.4,<1.5 django-tastypie==0.9.16"
  - MODULES="Django>=1.5,<1.6 django-tastypie>=0.10.0"
  - MODULES="Django>=1.6,<1.7 django-tastypie>=0.10.0"
# - MODULES="git+https://github.com/django/django.git@master#egg=django"

matrix:
  exclude:
    - python: "3.3"
      env: MODULES="Django>=1.4,<1.5 django-tastypie==0.9.16"
    # Remove the following two exclusions once SayIt is compatible with Python 3.
    - python: "3.3"
      env: MODULES="Django>=1.5,<1.6 django-tastypie>=0.10.0"
    - python: "3.3"
      env: MODULES="Django>=1.6,<1.7 django-tastypie>=0.10.0"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg libavcodec-extra-53 iceweasel xvfb yui-compressor
  - gem install --conservative --no-ri --no-rdoc sass -v 3.2.14
  - gem install --conservative --no-ri --no-rdoc compass -v 0.12.2
  - gem install --conservative --no-ri --no-rdoc zurb-foundation -v 4.3.2
  - pip install $MODULES
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database "sayit-example-project";' -U postgres
  - ./manage.py syncdb --noinput --migrate
  - ./manage.py collectstatic --noinput
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - SELENIUM_TESTS=1 ./manage.py test
