notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#sayit"
    use_notice: true

language: python

services:
  - elasticsearch

env:
  global:
    - CFLAGS="-O0"
  matrix:
    - TOXENV=flake8
    - TOXENV=py27-1.4
    - TOXENV=py27-1.7
    - TOXENV=py27-1.8
    - TOXENV=py27-1.9
    - TOXENV=py34-1.7
    - TOXENV=py34-1.8
    - TOXENV=py34-1.9

matrix:
  allow_failures:
    - env: TOXENV=py27-1.9
    - env: TOXENV=py34-1.9

install:
  - 'if [ $TOXENV != "flake8" ]; then sudo apt-get update -qq; fi'
  - 'if [ $TOXENV != "flake8" ]; then sudo apt-get install -qq ffmpeg libavcodec-extra-53 iceweasel xvfb; fi'
  - 'if [ $TOXENV != "py27-1.4" ]; then pip install tox; fi'
  - 'if [ $TOXENV == "py27-1.4" ]; then pip install "Django>=1.4,<1.5" django-tastypie==0.9.16; fi'
  - 'if [ $TOXENV == "py27-1.4" ]; then pip install -e .[test]; fi'

before_script:
  - psql -c 'create database "sayit-example-project";' -U postgres
  - export DISPLAY=:99.0
  - 'if [ $TOXENV != "flake8" ]; then sh -e /etc/init.d/xvfb start; fi'

script:
  - 'if [ $TOXENV == "py27-1.4" ]; then python manage.py test; fi'
  - 'if [ $TOXENV != "py27-1.4" ]; then tox; fi'
