notifications:
  email: false

language: python

services:
  - elasticsearch

env:
  global:
    - CFLAGS="-O0"
  matrix:
    - TOXENV=flake8
    - TOXENV=py-27-1.8
    - TOXENV=py-27-1.10
    - TOXENV=py-27-1.11
    - TOXENV=py-34-1.8
    - TOXENV=py-34-1.10
    - TOXENV=py-34-1.11

install:
  - 'if [ $TOXENV != "flake8" ]; then sudo apt-get update -qq; fi'
  - 'if [ $TOXENV != "flake8" ]; then sudo apt-get install -qq ffmpeg libavcodec-extra-53 iceweasel xvfb; fi'
  - pip install tox

before_script:
  - psql -c 'create database "sayit-example-project";' -U postgres
  - export DISPLAY=:99.0
  - 'if [ $TOXENV != "flake8" ]; then sh -e /etc/init.d/xvfb start; fi'

script:
  - tox
